In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
file_path = 'C:\\Users\\man\\Downloads\\base-contrat-complete.xlsm'
df = pd.read_excel(file_path, sheet_name='Base Complète')
df.head()

,année,Contrat_def,Classe d'usage,Description_du_Noeud,Date d'effet de Souscription,Prime_brute,Prime_nette,Prime Annuelle,RC_RTI,tot_prime_nette,Puissance,vv,VAN,Fractionnement,Type de souscription,Marque,Annee MEC,Age du véhicule,MEC
0,2023,10602001095,Affaire,MEHDI MEJRI,2022-12-23,609.862,506.153,506.153,220.0,506.153,4.0,15000,15000,Annuel,Au Tiers,CITROEN,2009.0,13.0,2009-10-07
1,2023,10602001097,Affaire,MEHDI MEJRI,2022-12-26,269.564,204.995,409.990,70.0,204.995,5.0,10000,10000,Semestriel,Au Tiers,PEUGEOT,2005.0,17.0,2005-10-06
2,2023,10602001098,Affaire,MEHDI MEJRI,2022-12-28,453.772,368.966,368.966,98.0,368.966,6.0,13000,13000,Annuel,Au Tiers,RENAULT,2002.0,21.0,2002-05-28
3,2023,10602001099,Affaire,MEHDI MEJRI,2022-12-28,810.934,687.620,1375.240,140.0,687.620,5.0,30000,30000,Semestriel,Tierce,TOYOTA,2021.0,1.0,2021-12-27
4,2023,10602001100,Utilitaire 1,MEHDI MEJRI,2022-12-30,878.969,746.145,746.145,235.8,746.145,8.0,45000,45000,Annuel,Au Tiers,ISUZU,2016.0,7.0,2016-06-24

In [3]:
# Check for missing values in each column
missing_values = df.isnull().sum()

# Print the missing values count for each column
print(missing_values)

# Remove rows with missing values (if necessary)
df_cleaned = df.dropna()

# Alternatively, replace missing values with the mean (for numerical columns)
# df.fillna(df.mean(), inplace=True)

année                              0
Contrat_def                        0
Classe d'usage                     0
Description_du_Noeud               0
Date d'effet de Souscription       0
Prime_brute                        1
Prime_nette                        0
Prime Annuelle                     0
RC_RTI                             0
tot_prime_nette                    0
Puissance                       2393
vv                               654
VAN                             2517
Fractionnement                   653
Type de souscription               0
Marque                           652
Annee MEC                        653
Age du véhicule                  653
MEC                              653
dtype: int64

In [4]:
# Step 1: Handle Outliers Using the IQR Method for specific columns

# List of columns to handle outliers
columns_to_check = ['Prime_brute', 'Prime_nette', 'Prime Annuelle', 'tot_prime_nette']

# Select only the specified numerical columns for outlier detection
df_selected = df_cleaned[columns_to_check]

# Calculate the IQR (Interquartile Range) for each column in the selected list
Q1 = df_selected.quantile(0.25)
Q3 = df_selected.quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for filtering out outliers for each column
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Create a mask to identify rows with outliers in the selected columns
mask_no_outliers = ~((df_selected < lower_bound) | (df_selected > upper_bound)).any(axis=1)

# Filter the original DataFrame to exclude rows with outliers in the specified columns
df_no_outliers_selected = df_cleaned[mask_no_outliers]


# Check the number of rows after removing the outliers
num_rows_after_outliers = df_no_outliers_selected.shape[0]
print(f"The number of rows after handling outliers: {num_rows_after_outliers}")

The number of rows after handling outliers: 26887

In [5]:
# Remove duplicate rows
df_no_duplicates = df_no_outliers_selected.drop_duplicates()

# Display the cleaned data after removing duplicates
print("Data after removing duplicates:")
df_no_duplicates.head()

Data after removing duplicates:

,année,Contrat_def,Classe d'usage,Description_du_Noeud,Date d'effet de Souscription,Prime_brute,Prime_nette,Prime Annuelle,RC_RTI,tot_prime_nette,Puissance,vv,VAN,Fractionnement,Type de souscription,Marque,Annee MEC,Age du véhicule,MEC
0,2023,10602001095,Affaire,MEHDI MEJRI,2022-12-23,609.862,506.153,506.153,220.0,506.153,4.0,15000,15000,Annuel,Au Tiers,CITROEN,2009.0,13.0,2009-10-07
1,2023,10602001097,Affaire,MEHDI MEJRI,2022-12-26,269.564,204.995,409.990,70.0,204.995,5.0,10000,10000,Semestriel,Au Tiers,PEUGEOT,2005.0,17.0,2005-10-06
2,2023,10602001098,Affaire,MEHDI MEJRI,2022-12-28,453.772,368.966,368.966,98.0,368.966,6.0,13000,13000,Annuel,Au Tiers,RENAULT,2002.0,21.0,2002-05-28
4,2023,10602001100,Utilitaire 1,MEHDI MEJRI,2022-12-30,878.969,746.145,746.145,235.8,746.145,8.0,45000,45000,Annuel,Au Tiers,ISUZU,2016.0,7.0,2016-06-24
7,2023,10602001103,Utilitaire 1,MEHDI MEJRI,2023-01-05,566.668,467.900,935.800,202.5,467.900,17.0,40000,40000,Semestriel,Au Tiers,ISUZU,2019.0,4.0,2019-03-26

In [6]:
# Get the number of rows after cleaning outliers and duplicates
num_rows_after_cleaning = df_no_duplicates.shape[0]
print(f"The number of rows after cleaning: {num_rows_after_cleaning}")

The number of rows after cleaning: 26887

In [7]:
# Save the cleaned data to the specified directory
df_no_duplicates.to_excel(r'C:\Users\man\Downloads\cleaned_data_final.xlsx', index=False)